version: 0.0
os: linux
files:
  - source: ./target/resources-demo-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user

hooks:
  ApplicationStop:
    - location: stop.sh
      timeout: 20
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 20
      runas: ec2-user
  ValidateService:
    - location: validate.sh
      timeout: 120
      runas: ec2-user
