version: 0.0
os: linux
files:
  - source: resources-demo-0.0.1-SNAPSHOT.jar

hooks:
  ApplicationStart:
    - location: start.sh
      timeout: 20
      runas: ec2-user
  ValidateService:
    - location: validate.sh
      timeout: 120
      runas: ec2-user
